/// <summary>
/// An enumeration of the audio clip names. Used to load wav files.
/// </summary>
public enum AudioClipName
{
    Music_Battle_Theme,
    Music_Devils_Lab,
    Music_Fanfare,
    Music_Kids_Run_Through_The_City,
    Music_Mt_Koltz,
    Music_New_Continent,
    Music_Save_Them,
    Music_Terra,
    Music_The_Decisive_Battle,
    Music_The_Fierce_Battle,
    Music_The_Mines_Of_Narshe,
    Music_The_Phantom_Forest,
    Music_The_Phantom_Train,
    Music_The_Unforgiven,
    Music_The_Wedding_Waltz_Duel_4,
    Music_Wild_West,
    Boom,
    BossDeath,
    Crossbow_Bolt,
    Cure,
    Defend,
    Drill,
    Encounter,
    Fight,
    Kick,
    MenuChirp0,
    MenuChirp1,
    MenuChirp2,
    MenuChirp3,
    MenuChirp4,
    MenuChirp5,
    Miss,
    Opening_Theme_1,
    Rest_In_Peace, 
    RunAway,
    Runic,
    Save,
    ShopPurchase,
    ThiefSteal,
    TrainHorn,
    UsePotion,
    UseTome

}
